version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_netflix_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
